# Generated by Django 5.1.7 on 2025-03-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='url',
            name='senha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
